# Generated by Django 4.1.3 on 2022-12-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='male', max_length=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.TextField(default='https://firebasestorage.googleapis.com/v0/b/web-projs-122ec.appspot.com/o/profile%2Fundraw_Female_avatar_re_l6cx.png?alt=media&token=378fc2d8-bdd6-47be-88e1-f790941e2169|\nhttps://firebasestorage.googleapis.com/v0/b/web-projs-122ec.appspot.com/o/profile%2Fundraw_Male_avatar_re_y880.png?alt=media&token=ad0ac38c-5b35-4bb4-92bc-1b3a377f66e0\n'),
        ),
    ]
