# Generated by Django 4.1.3 on 2022-12-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_sex_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.TextField(default='https://firebasestorage.googleapis.com/v0/b/web-projs-122ec.appspot.com/o/profile%2Fundraw_Male_avatar_re_y880.png?alt=media&token=ad0ac38c-5b35-4bb4-92bc-1b3a377f66e0'),
        ),
    ]
