# Generated by Django 4.1.3 on 2022-12-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_listings_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primary_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
