# Generated by Django 4.1.3 on 2022-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
