# Generated by Django 4.1.3 on 2022-12-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_listings_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
