# Generated by Django 4.1.3 on 2022-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_listings_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='available',
        ),
        migrations.AddField(
            model_name='listing',
            name='funished',
            field=models.BooleanField(default=True),
        ),
    ]
