# Generated by Django 4.1.3 on 2022-12-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_listing_date_listed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='funished',
            new_name='furnished',
        ),
    ]
