# Generated by Django 4.1.3 on 2022-12-13 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_funished_listing_furnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default=uuid.uuid5, primary_key=True, serialize=False),
        ),
    ]
