# Generated by Django 4.1.3 on 2022-12-13 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='display_image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
