# Generated by Django 4.1.3 on 2022-12-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_listing_display_image_alter_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='', max_length=12),
        ),
    ]
